function lesson1() {
    document.getElementById("lesson1Content").style.display = "block";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson2() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "block";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson3() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "block";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson4() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "block";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson5() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "block";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson6() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("nextButton5").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson6").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "block";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson7() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("nextButton5").style.display = "none";
    document.getElementById("nextButton6").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson6").disabled = false;
    document.getElementById("lesson7").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "block";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson8() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("nextButton5").style.display = "none";
    document.getElementById("nextButton6").style.display = "none";
    document.getElementById("nextButton7").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson6").disabled = false;
    document.getElementById("lesson7").disabled = false;
    document.getElementById("lesson8").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "block";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson9() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("nextButton5").style.display = "none";
    document.getElementById("nextButton6").style.display = "none";
    document.getElementById("nextButton7").style.display = "none";
    document.getElementById("nextButton8").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson6").disabled = false;
    document.getElementById("lesson7").disabled = false;
    document.getElementById("lesson8").disabled = false;
    document.getElementById("lesson9").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "block";
    document.getElementById("lesson10Content").style.display = "none";
    document.getElementById("finalExamContent").style.display = "none";
  }

  function lesson10() {
    document.getElementById("nextButton1").style.display = "none";
    document.getElementById("nextButton2").style.display = "none";
    document.getElementById("nextButton3").style.display = "none";
    document.getElementById("nextButton4").style.display = "none";
    document.getElementById("nextButton5").style.display = "none";
    document.getElementById("nextButton6").style.display = "none";
    document.getElementById("nextButton7").style.display = "none";
    document.getElementById("nextButton8").style.display = "none";
    document.getElementById("nextButton9").style.display = "none";
    document.getElementById("lesson2").disabled = false;
    document.getElementById("lesson3").disabled = false;
    document.getElementById("lesson4").disabled = false;
    document.getElementById("lesson5").disabled = false;
    document.getElementById("lesson6").disabled = false;
    document.getElementById("lesson7").disabled = false;
    document.getElementById("lesson8").disabled = false;
    document.getElementById("lesson9").disabled = false;
    document.getElementById("lesson10").disabled = false;
    document.getElementById("lesson1Content").style.display = "none";
    document.getElementById("lesson2Content").style.display = "none";
    document.getElementById("lesson3Content").style.display = "none";
    document.getElementById("quiz1Content").style.display = "none";
    document.getElementById("lesson4Content").style.display = "none";
    document.getElementById("lesson5Content").style.display = "none";
    document.getElementById("quiz2Content").style.display = "none";
    document.getElementById("lesson6Content").style.display = "none";
    document.getElementById("lesson7Content").style.display = "none";
    document.getElementById("lesson8Content").style.display = "none";
    document.getElementById("quiz3Content").style.display = "none";
    document.getElementById("lesson9Content").style.display = "none";
    document.getElementById("lesson10Content").style.display = "block";
    document.getElementById("finalExamContent").style.display = "none";
  }